kind: Service
apiVersion: v1
metadata:
  name: local-volume-csi-resizer
  namespace: kube-system
  labels:
    app: local-volume-csi-resizer
spec:
  selector:
    app: local-volume-csi-resizer
  ports:
    - name: dummy
      port: 12345

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: local-volume-csi-resizer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: local-volume-csi-resizer
  serviceName: local-volume-csi-resizer
  template:
    metadata:
      labels:
        app: local-volume-csi-resizer
    spec:
      tolerations:
      - operator: "Exists"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      priorityClassName: system-node-critical
      serviceAccount: local-volume-csi-driver-service-account
      hostNetwork: true
      containers:
        - name: local-volume-csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /socketDir/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /socketDir/
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/local.volume.csi.kubernetes.io
            type: DirectoryOrCreate
  updateStrategy:
    type: RollingUpdate
