/*
Copyright 2019 JD Cloud

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-local-volume/kubernetes-local-volume/pkg/apis/storage/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeInfos implements NodeInfoInterface
type FakeNodeInfos struct {
	Fake *FakeLocalV1alpha1
	ns   string
}

var nodeinfosResource = schema.GroupVersionResource{Group: "local.volume.storage", Version: "v1alpha1", Resource: "nodeinfos"}

var nodeinfosKind = schema.GroupVersionKind{Group: "local.volume.storage", Version: "v1alpha1", Kind: "NodeInfo"}

// Get takes name of the nodeInfo, and returns the corresponding nodeInfo object, and an error if there is any.
func (c *FakeNodeInfos) Get(name string, options v1.GetOptions) (result *v1alpha1.NodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodeinfosResource, c.ns, name), &v1alpha1.NodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeInfo), err
}

// List takes label and field selectors, and returns the list of NodeInfos that match those selectors.
func (c *FakeNodeInfos) List(opts v1.ListOptions) (result *v1alpha1.NodeInfoList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodeinfosResource, nodeinfosKind, c.ns, opts), &v1alpha1.NodeInfoList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeInfoList{ListMeta: obj.(*v1alpha1.NodeInfoList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeInfoList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeInfos.
func (c *FakeNodeInfos) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodeinfosResource, c.ns, opts))

}

// Create takes the representation of a nodeInfo and creates it.  Returns the server's representation of the nodeInfo, and an error, if there is any.
func (c *FakeNodeInfos) Create(nodeInfo *v1alpha1.NodeInfo) (result *v1alpha1.NodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodeinfosResource, c.ns, nodeInfo), &v1alpha1.NodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeInfo), err
}

// Update takes the representation of a nodeInfo and updates it. Returns the server's representation of the nodeInfo, and an error, if there is any.
func (c *FakeNodeInfos) Update(nodeInfo *v1alpha1.NodeInfo) (result *v1alpha1.NodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodeinfosResource, c.ns, nodeInfo), &v1alpha1.NodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeInfo), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeInfos) UpdateStatus(nodeInfo *v1alpha1.NodeInfo) (*v1alpha1.NodeInfo, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodeinfosResource, "status", c.ns, nodeInfo), &v1alpha1.NodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeInfo), err
}

// Delete takes name of the nodeInfo and deletes it. Returns an error if one occurs.
func (c *FakeNodeInfos) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodeinfosResource, c.ns, name), &v1alpha1.NodeInfo{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeInfos) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodeinfosResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeInfoList{})
	return err
}

// Patch applies the patch and returns the patched nodeInfo.
func (c *FakeNodeInfos) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodeInfo, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodeinfosResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodeInfo{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeInfo), err
}
