/*
Copyright 2019 JD Cloud

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubernetes-local-volume/kubernetes-local-volume/pkg/apis/storage/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeLocalVolumeStorages implements NodeLocalVolumeStorageInterface
type FakeNodeLocalVolumeStorages struct {
	Fake *FakeLocalV1alpha1
	ns   string
}

var nodelocalvolumestoragesResource = schema.GroupVersionResource{Group: "local.volume.storage", Version: "v1alpha1", Resource: "nodelocalvolumestorages"}

var nodelocalvolumestoragesKind = schema.GroupVersionKind{Group: "local.volume.storage", Version: "v1alpha1", Kind: "NodeLocalVolumeStorage"}

// Get takes name of the nodeLocalVolumeStorage, and returns the corresponding nodeLocalVolumeStorage object, and an error if there is any.
func (c *FakeNodeLocalVolumeStorages) Get(name string, options v1.GetOptions) (result *v1alpha1.NodeLocalVolumeStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodelocalvolumestoragesResource, c.ns, name), &v1alpha1.NodeLocalVolumeStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeLocalVolumeStorage), err
}

// List takes label and field selectors, and returns the list of NodeLocalVolumeStorages that match those selectors.
func (c *FakeNodeLocalVolumeStorages) List(opts v1.ListOptions) (result *v1alpha1.NodeLocalVolumeStorageList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodelocalvolumestoragesResource, nodelocalvolumestoragesKind, c.ns, opts), &v1alpha1.NodeLocalVolumeStorageList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeLocalVolumeStorageList{ListMeta: obj.(*v1alpha1.NodeLocalVolumeStorageList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeLocalVolumeStorageList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeLocalVolumeStorages.
func (c *FakeNodeLocalVolumeStorages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodelocalvolumestoragesResource, c.ns, opts))

}

// Create takes the representation of a nodeLocalVolumeStorage and creates it.  Returns the server's representation of the nodeLocalVolumeStorage, and an error, if there is any.
func (c *FakeNodeLocalVolumeStorages) Create(nodeLocalVolumeStorage *v1alpha1.NodeLocalVolumeStorage) (result *v1alpha1.NodeLocalVolumeStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodelocalvolumestoragesResource, c.ns, nodeLocalVolumeStorage), &v1alpha1.NodeLocalVolumeStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeLocalVolumeStorage), err
}

// Update takes the representation of a nodeLocalVolumeStorage and updates it. Returns the server's representation of the nodeLocalVolumeStorage, and an error, if there is any.
func (c *FakeNodeLocalVolumeStorages) Update(nodeLocalVolumeStorage *v1alpha1.NodeLocalVolumeStorage) (result *v1alpha1.NodeLocalVolumeStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodelocalvolumestoragesResource, c.ns, nodeLocalVolumeStorage), &v1alpha1.NodeLocalVolumeStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeLocalVolumeStorage), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeLocalVolumeStorages) UpdateStatus(nodeLocalVolumeStorage *v1alpha1.NodeLocalVolumeStorage) (*v1alpha1.NodeLocalVolumeStorage, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodelocalvolumestoragesResource, "status", c.ns, nodeLocalVolumeStorage), &v1alpha1.NodeLocalVolumeStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeLocalVolumeStorage), err
}

// Delete takes name of the nodeLocalVolumeStorage and deletes it. Returns an error if one occurs.
func (c *FakeNodeLocalVolumeStorages) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodelocalvolumestoragesResource, c.ns, name), &v1alpha1.NodeLocalVolumeStorage{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeLocalVolumeStorages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodelocalvolumestoragesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeLocalVolumeStorageList{})
	return err
}

// Patch applies the patch and returns the patched nodeLocalVolumeStorage.
func (c *FakeNodeLocalVolumeStorages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodeLocalVolumeStorage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodelocalvolumestoragesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodeLocalVolumeStorage{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeLocalVolumeStorage), err
}
