// +build !ignore_autogenerated

/*
Copyright 2019 JD Cloud

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLocalVolumeStorage) DeepCopyInto(out *NodeLocalVolumeStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLocalVolumeStorage.
func (in *NodeLocalVolumeStorage) DeepCopy() *NodeLocalVolumeStorage {
	if in == nil {
		return nil
	}
	out := new(NodeLocalVolumeStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeLocalVolumeStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLocalVolumeStorageList) DeepCopyInto(out *NodeLocalVolumeStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeLocalVolumeStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLocalVolumeStorageList.
func (in *NodeLocalVolumeStorageList) DeepCopy() *NodeLocalVolumeStorageList {
	if in == nil {
		return nil
	}
	out := new(NodeLocalVolumeStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeLocalVolumeStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLocalVolumeStorageSpec) DeepCopyInto(out *NodeLocalVolumeStorageSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLocalVolumeStorageSpec.
func (in *NodeLocalVolumeStorageSpec) DeepCopy() *NodeLocalVolumeStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NodeLocalVolumeStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeLocalVolumeStorageStatus) DeepCopyInto(out *NodeLocalVolumeStorageStatus) {
	*out = *in
	if in.PreAllocated != nil {
		in, out := &in.PreAllocated, &out.PreAllocated
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeLocalVolumeStorageStatus.
func (in *NodeLocalVolumeStorageStatus) DeepCopy() *NodeLocalVolumeStorageStatus {
	if in == nil {
		return nil
	}
	out := new(NodeLocalVolumeStorageStatus)
	in.DeepCopyInto(out)
	return out
}
